backend:
  name: github
  repo: friday-fish/friday-fish.github.io
output:
  omit_empty_optional_fields: true
  yaml:
    quote: double
media_folder: "notes"
collections:
  - name: "talk"
    label: "Talk"
    folder: "_talks"
    create: true
    summary: "{{speaker}}: {{title}} (on {{date | date('YYYY-MM-DD')}})"
    editor:
      preview: false
    slug: "{{date | date('YYYY-MM-DD')}}-{{speaker}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "talk" }
      - { label: "Date", name: "date", widget: "datetime", type: date }
      - { label: "Starting time", name: "start_time", widget: "string", default: "15:00" }
      - { label: "Ending time", name: "end_time", widget: "string", default: "17:00" }
      - { label: "Location", name: "location", widget: "string", default: "HFG 707" }
      - { label: "Speaker", name: "speaker", widget: "string" }
      - { label: "Affiliation", name: "affiliation", widget: "string", required: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Abstract", name: "abstract", widget: "richtext" }
      - { label: "Video URL", name: "video_url", widget: "string", required: false }
      - { label: "Notes", name: "notes_url", widget: "file", required: false }
      - { label: "Slides", name: "slides_url", widget: "file", media_folder: "slides", required: false }
      - { label: "Reading seminar", name: "seminar", widget: "relation", required: false, collection: "reading-seminar", value_field: "key", display_fields: [ "title" ] }
  - name: "reading-seminar"
    label: "Reading seminar"
    folder: "_reading_seminars"
    create: true
    summary: "{{title}}"
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "reading_seminar" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Key", name: "key", widget: "string" }
      - { label: "Active", name: "active", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "richtext" }
  - name: "announcements"
    label: "Announcements"
    folder: "_posts"
    create: true
    summary: "{{title}}"
    editor:
      preview: false
    slug: "{{date | date('YYYY-MM-DD')}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Date", name: "date", widget: "datetime", type: "date" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Active", name: "active", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "richtext" }
